### ISSUE TITLE
Andre your email is not working

### ISSUE THREAD

**Issue by martindb** [andref/Unnatural-Sublime-Package#1]
hi Andre,

your email [andre@filli.pe](mailto:andre@filli.pe) is not working. I whould like to contact you.

Thanks,
Martin

**Comment by andref** [comment]
Hi @martindb! How can I help?

**Comment by martindb** [comment]
Hi Andre,

I'm working as a devops engineer in a legacy Natural/Adabas environment, currently implementing the CI/CD pipelines for this technology that we are migrating to Linux (from AIX).

Our developers will work with NaturalONE for the natural code and related objects, but we will use Visual Studio Code for Cobol (aka migrating to GNUCobol) and the batch scripts (ksh bases, very similar to the MainFrame JCL we have 15 year ago).

I will try to develop a very basic Natural extension for Visual Studio Code using your Textmate syntax, snippets, and so. The idea is to make VS more friendly to Natural code, but not to replace NaturalONE (at least not in the beginning).

Best regards,
Martin

**Comment by andref** [comment]
Nice! Is there anything specific you might need?

**Comment by martindb** [comment]
No, just know that I'll be taking part of your work. The extension will be published on github under the same license as your module (MIT License).
Thank you for your work!

**Comment by andref** [comment]
Oh, right! I wish you and your team all the best and hope the code here can be of use. Cheers!
